# ---- Create Test Data ----
test <- tibble(word = c("+441234567890",
                        "01234567890",
                        "+453948403890",
                        "0344 871 8000",
                        "M50 2GT",
                        "M502GT",
                        "John",
                        "Jasmin",
                        "Rupert",
                        "Walker",
                        "rupert.walker@fakemail.com",
                        "notagain@example.com",
                        "123 Fake Street",
                        "Imaginary Lane",
                        "20-10-10",
                        "03/06/1992",
                        "14-11-1893",
                        "some",
                        "extremely",
                        "running",
                        "apple",
                        "banana",
                        "bananas",
                        "word",
                        "words"))

test2 <- c("+441234567890",
           "01234567890",
           "+453948403890",
           "0344 871 8000",
           "M50 2GT",
           "M502GT",
           "John",
           "Jasmin",
           "Rupert",
           "Walker",
           "rupert.walker@fakemail.com",
           "notagain@example.com",
           "123 Fake Street",
           "Imaginary Lane",
           "20-10-10",
           "03/06/1992",
           "14-11-1893",
           "some",
           "extremely",
           "running",
           "apple",
           "banana",
           "bananas",
           "word",
           "words")
